defaults:
  - _self_
  - loader: loader
  - loss: scfe_regularization
  - model: bmlp    # mlp - water or cnn - cifar10
  - logger: wandb
  - data: water
  - trainer: trainer_default
  - optimizer: sgd
  - estimator: scfe
  - preprocessor: preprocessing

run_mode: sweep #run       
project: cfreg_noisy_setting
name: experiments
version: 1
seed: 42
device: cuda