defaults:
  - _self_
  - loader: loader
  - loss: normal
  - model: bpreactresnet    # mlp - water or cnn - cifar10
  - logger: wandb
  - data: mnist
  - trainer: trainer_default
  - optimizer: sgd
  - estimator: scfe
  - preprocessor: preprocessing

run_mode: run #sweep      
project: counterfactual_overfitting_experiments_new
name: experiments
version: 1
seed: 42
device: cuda