method: grid
name: best_higgs_reduced_mlps_l1_configurations
metric:
  goal: maximize
  name: test/accuracy
parameters:
  tuning:
    value: false
  data.name:
    value: higgs_reduced
  preprocessor.poly_features_degree:
    value: 1
  trainer.max_epochs:
    value: 200
  model.model_type:
    value: BMLP
  model.hidden_layers:
    value: [100, 30]
  model.dropout:
    value: 0.0
  loss.type:
    value: l1normal
  loss.alpha:
    values:
      - 0.04422047463915662
      - 0.789026550159694
