method: grid
name: best_water_lr_earlystopping_configurations
metric:
  goal: maximize
  name: test/accuracy
parameters:
  tuning:
    value: false
  data.name:
    value: water
  preprocessor.poly_features_degree:
    value: 6
  trainer.max_epochs:
    value: 2000
  model.model_type:
    value: LogisticRegression
  loss.type:
    value: normal
  trainer.callbacks:
    values:
      - {early_stop_enable: true, patience: 35}
      - {early_stop_enable: true, patience: 20}
