method: grid
name: best_phomene_mlps_l2_configurations
metric:
  goal: maximize
  name: test/accuracy
parameters:
  tuning:
    value: false
  data.name:
    value: phomene
  preprocessor.poly_features_degree:
    value: 1
  trainer.max_epochs:
    value: 2000
  model.model_type:
    value: BMLP
  model.hidden_layers:
    value: [100, 30]
  model.dropout:
    value: 0.0
  loss.type:
    value: l2normal
  loss.alpha:
    values:
      - 0.00021544129472565336
      - 0.00014809202317603347
