method: grid
name: best_phomene_lr_l2_configurations
metric:
  goal: maximize
  name: test/accuracy
parameters:
  tuning:
    value: false
  data.name:
    value: phomene
  preprocessor.poly_features_degree:
    value: 11
  trainer.max_epochs:
    value: 2000
  model.model_type:
    value: LogisticRegression
  loss.type:
    value: l2normal
  loss.alpha:
    values:
      - 0.000101981138999573
      - 0.0001464223258861936
