method: grid
name: final_water_lr_scfe_configuration_3
metric:
  goal: maximize
  name: test/accuracy
parameters:
  seed:
    values:
    - 42
    - 43
    - 44
    - 45
    - 46
  tuning:
    value: false
  data.name:
    value: water
  preprocessor.poly_features_degree:
    value: 6
  trainer.max_epochs:
    value: 2000
  model.model_type:
    value: LogisticRegression
  loss.type:
    value: scfe_regularization
  loss.alpha:
    value: -0.2690243594537942
  estimator.type:
    value: scfe
  estimator.reg_coef.value:
    value: 0.3180138025733559
