method: grid
name: final_cifar10_l1_configuration
metric:
  goal: maximize
  name: test/accuracy
parameters:
  seed:
    values:
    - 42
    - 43
    - 44
    - 45
    - 46
  tuning:
    value: false
  data.name:
    value: cifar10
  trainer.max_epochs:
    value: 200
  model.model_type:
    value: BPreActResNet
  loss.type:
    value: l1normal
  loss.alpha:
    value: 0.22835150478944136
